import { Inter } from "next/font/google";
import "./globals.css";

import ThemeProvider from '../Providers/ThemeProvider'
import Navbar from "@/components/Navbar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-white text-black  dark:bg-black dark:text-white">
        
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <Navbar />
            {children}
          </ThemeProvider>

      </body>
    </html>
  );
}
